version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: bin/build
     timeout: 300
     runas: admin
  ApplicationStart:
   - location: bin/run
     timeout: 300
     runas: admin
