version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/app
hooks:
  AfterInstall:
    - location: bin/build
      timeout: 5000
      runas: ubuntu
  ApplicationStart:
    - location: bin/deploy
      timeout: 5000
      runas: ubuntu
