version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/app
hooks:
  AfterInstall:
   - location: bin/build
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: bin/run
     timeout: 300
     runas: ubuntu
