# Only define shared info in this file
version: "3.9"
services:
  api:
    build:
      context: $PWD
      dockerfile: api/Dockerfile
    ports:
      - "80"
      - "8080"
  extension:
    build:
      context: $PWD
      dockerfile: extension/Dockerfile
    volumes:
      - $PWD/extension/src:/extension/src
      - $PWD/extension/dist:/extension/dist
      - $PWD/common:/common
      - $PWD/extension/package.json:/extension/package.json
      - $PWD/extension/package-lock.json:/extension/package-lock.json
