version: "3.9"
services:
  migrations:
    image: com2027.migrations
    build:
      context: $PWD
      dockerfile: api/Dockerfile
      target: migrations
    restart: "no"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      DB_DATABASE: ${DB_DATABASE}
      SEED: ${SEED}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ 'setup' ]
  api:
    image: com2027.prod.api
    build:
      target: api
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      DB_DATABASE: ${DB_DATABASE}
      SEED: ${SEED}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ 'core' ]
  caddy:
    image: com2027.prod.caddy
    build:
      context: $PWD
      dockerfile: frontend/Dockerfile
      target: frontend
    restart: "no"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data:Z
      - caddy_config:/config:Z
    profiles: [ 'core' ]
  extension:
    image: com2027.prod.extension
    build:
      target: extension
    restart: 'no'
    profiles: [ 'setup' ]
volumes:
  caddy_data:
  caddy_config:
