version: 2.1

orbs: 
  discord: antonioned/discord@0.1.0

jobs:
  setup_and_run:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run:
          name: "setup"
          command: "cd frontend; npm install;"
      - run:
          name: "run"
          command: "pwd; cd frontend; ./entrypoint.sh npm run test"
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - discord/status:
          failure_message: "**${CIRCLE_USERNAME}** pushed bad code. The **$CIRCLE_JOB** job has failed! **You know what happens now :D**."
          success_message: "Good job **${CIRCLE_USERNAME}**, your code didn't break shit up. You get to live another day :)."
          webhook: "https://discord.com/api/webhooks/945465161555263499/JcDqy-CYDEnnVJr5gTLgi39QWj8VWpEaDwTzxDRbdyR0qgDh0kHsP1cHtfDl6-hqPgoO"



workflows:
  run:
    jobs:
      - setup_and_run
      - notify:
          requires:
            - setup_and_run


